### ISSUE TITLE
(VPM) Unspecified `com.unity.postprocessing` dependency

### ISSUE THREAD

**Issue by rrazgriz** [oneVR/VRWorldToolkit#18]
The `vpm` branch relies on the package `com.unity.postprocessing` being present, but the package is not listed as a dependency. This causes issues when importing to a base Avatars VCC project, as the Avatars SDK package does not contain `com.unity.postprocessing` as a dependency, but the Worlds SDK package does.
![Unity_fhSkqD8oNF](https://user-images.githubusercontent.com/47901762/205527930-fc36e621-c1db-4c17-977a-cca99a3ffaf7.png)

Define guards are present on the `master` branch, with a menu item for importing the post-processing package:
https://github.com/oneVR/VRWorldToolkit/blob/master/Scripts/Editor/WorldDebugger.cs#L10
https://github.com/oneVR/VRWorldToolkit/blob/master/Scripts/Editor/PostProcessingTools.cs#L6

These have been removed in the `vpm` branch:
https://github.com/oneVR/VRWorldToolkit/blob/vpm/Editor/WorldDebugger.cs#L23
https://github.com/oneVR/VRWorldToolkit/blob/vpm/Editor/PostProcessingTools.cs#L6

This can be fixed either by re-adding the define guards and menu option, or by adding `com.unity.postprocessing` as a dependency.

**Comment by oneVR** [comment]
Thank you for the report and PR! Merged #19
