### ISSUE TITLE
ArgumentNullException: Value cannot be null. error

### ISSUE THREAD

**Issue by InuYasha86000** [oneVR/VRWorldToolkit#30]
I keep getting these errors within the console after using the mass texture importer function:

ArgumentNullException: Value cannot be null.
Parameter name: unityObject
VRC.Udon.Serialization.OdinSerializer.UnitySerializationUtility.SerializeUnityObject (UnityEngine.Object unityObject, VRC.Udon.Serialization.OdinSerializer.SerializationData& data, System.Boolean serializeUnityFields, VRC.Udon.Serialization.OdinSerializer.SerializationContext context) (at ./Packages/com.vrchat.worlds/Runtime/Udon/Serialization/OdinSerializer/Unity Integration/UnitySerializationUtility.cs:1031)
UdonSharp.UdonSharpBehaviour.UnityEngine.ISerializationCallbackReceiver.OnBeforeSerialize () (at ./Packages/com.vrchat.worlds/Integrations/UdonSharp/Runtime/UdonSharpBehaviour.cs:286)
UnityEditor.AssetDatabase:StopAssetEditing()
VRWorldToolkit.Editor.ImporterSettingsManager:ProcessTextures(TextureDetails) (at ./Packages/dev.onevr.vrworldtoolkit/Editor/MassTextureImporter.cs:338)
VRWorldToolkit.Editor.MassTextureImporter:OnGUI() (at ./Packages/dev.onevr.vrworldtoolkit/Editor/MassTextureImporter.cs:408)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

This is using the current version 3.2.0 with worlds and base on 3.7.3 under windows build.
I got this error 574 times in a row using it once.

**Comment by oneVR** [comment]
I couldn't replicate this in a project with the VRChat SDK version you specified, so I might need more information on what's happening. It seems like there is some weird clash between it and UdonSharp or OdinSerializer in your project.
- Are you able to provide full repro steps for an empty project?
- Does this happen every time you try to run the importer?
- Is it possible you were in Play Mode while attempting to run it?
- Was 574 the amount of textures you were attempting to process?
- Was anything else (UdonSharp for example) doing something while you attempted to run it?

**Comment by InuYasha86000** [comment]
for an empty project, no sadly. I only noticed this happen tonight.
I was not in play mode for sure.
574 was not the amount of textures I was attempting to process, it's possible that's the amount in the project itself?
and no other udon scripts were running as far as I am aware.

**Comment by InuYasha86000** [comment]
I just ran the importer tonight and it still did the same thing. it DOES import the new textures as it should. could it be that I have the option "Don't Override When" set to "Already Enabled"?

**Comment by oneVR** [comment]
Thank you for all the information. However, since the errors are happening from Udon Sharp and Odin on the asset import, which isn't directly related to what my toolkit is doing, I might have to mark this as a won't fix for now. All my code is calling here is [StopAssetEditing](https://docs.unity3d.com/ScriptReference/AssetDatabase.StopAssetEditing.html), which processes all the changes made to the textures processed. The errors are a bit ugly, but if there are no actual issues coming from them, it might just be something to deal with.

You mentioned the textures import properly, did you notice any other issues coming from the errors?

**Comment by InuYasha86000** [comment]
no I have not. later today i'll open the project back up and try get a shot of the full error.

**Comment by oneVR** [comment]
Closing this out since it does not appear to be an issue with the Toolkit itself.
