### ISSUE TITLE
Unity 2019

### ISSUE THREAD

**Issue by rets34** [oneVR/VRWorldToolkit#9]
'Build Report' area blank on new VRChat Unity 2019 update.

**Comment by TheZiver** [comment]
yup, same here : (

**Comment by Belphagore** [comment]
Same result, here is an error message and stack associated with the issue when trying to open build report:

`ArgumentException: Getting control 0's position in a group with only 0 controls when doing repaint
Aborting
UnityEngine.GUILayoutGroup.GetNext () (at <023156577e4f4156adf0f4b3a3fedf85>:0)
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at <023156577e4f4156adf0f4b3a3fedf85>:0)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.EditorGUILayout+HorizontalScope..ctor (UnityEngine.GUILayoutOption[] options) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
VRWorldToolkit.WorldDebugger.DrawBuildReportOverviews (UnityEngine.Event current) (at Assets/VRWorldToolkit/Scripts/Editor/WorldDebugger.cs:2949)
VRWorldToolkit.WorldDebugger.OnGUI () (at Assets/VRWorldToolkit/Scripts/Editor/WorldDebugger.cs:2930)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.DockArea.OldOnGUI () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Boolean straightY, System.Single pixelsPerPoint, System.Exception& immediateException) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
Rethrow as ImmediateModeException
UnityEngine.UIElements.UIR.RenderChain.Render (UnityEngine.Rect viewport, UnityEngine.Matrix4x4 projection, UnityEngine.UIElements.PanelClearFlags clearFlags) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIRRepaintUpdater.DrawChain (UnityEngine.Rect viewport, UnityEngine.Matrix4x4 projection) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIRRepaintUpdater.Update () (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.Panel.UpdateForRepaint () (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <023156577e4f4156adf0f4b3a3fedf85>:0)`

**Comment by rets34** [comment]
Same here, mine back and forths between that error and this one:
`InvalidOperationException: TreeView: 'rootItem.children == null'. Did you forget to add children? If you intend to only create the list of rows (not the full tree) then you need to override: BuildRows, GetAncestors and GetDescendantsThatHaveChildren.
UnityEditor.IMGUI.Controls.TreeView+TreeViewControlDataSource.ValidateRootItem () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.IMGUI.Controls.TreeView+TreeViewControlDataSource.FetchData () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.IMGUI.Controls.TreeViewDataSource.ReloadData () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.IMGUI.Controls.TreeView+TreeViewControlDataSource.ReloadData () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.IMGUI.Controls.TreeViewController.ReloadData () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.IMGUI.Controls.TreeView.Reload () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
VRWorldToolkit.BuildReportTreeView..ctor (UnityEditor.IMGUI.Controls.TreeViewState state, UnityEditor.IMGUI.Controls.MultiColumnHeader multiColumnHeader, UnityEditor.Build.Reporting.BuildReport report) (at Assets/VRWorldToolkit/Scripts/Editor/BuildReportTreeView.cs:36)
VRWorldToolkit.WorldDebugger.InitWhenNeeded () (at Assets/VRWorldToolkit/Scripts/Editor/WorldDebugger.cs:2842)
VRWorldToolkit.WorldDebugger.OnGUI () (at Assets/VRWorldToolkit/Scripts/Editor/WorldDebugger.cs:2926)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.DockArea.OldOnGUI () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

**Comment by oneVR** [comment]
I will be releasing a new version that fixes Unity 2019 compatibility later today or tomorrow.

**Comment by oneVR** [comment]
Latest release has been fixed for Unity 2019
